### PR TITLE
Fixes and new methods for text/xml reports and text/pdf receipts view

### PR DESCRIPTION
**Pull request by dimaloop**
According to the [docs](https://dev-api.checkbox.in.ua/api/redoc#operation/create_receipt_api_v1_receipts_sell_post) - CARD type deprecated, so removed

### CODE REVIEW

**Comment by dimaloop** [comment]
also added related_receipt_id and previous_receipt_id fields to ReceiptSellPayload according [docs](https://dev-api.checkbox.in.ua/api/redoc#operation/create_receipt_api_v1_receipts_sell_post)

**Comment by dimaloop** [comment]
[+] getReportTextById method for text report view
[+] getReportXMLById method for xml report view
[+] getForString private service method for getting content without json mapper
update version to 1.10.7

**Comment by dimaloop** [comment]
[+] getReceiptTextById method for text receipt view
[+] getReceiptPdfById method for pdf receipt view

**Comment by dimaloop** [comment]
Fix getReceiptPdfById method to work with byte[] instead String:

There were only methods for working with string body: HttpResponse.BodyHandlers.ofString()

I added a method to work with bytes

Perhaps other committers will have ideas for unification  of getForObjectImpl - I will gladly accept ideas!

**Comment by dimaloop** [comment]
[+] getReceiptPngById method for PNG receipt view with optional paper/content width
[+] getReceiptQRCodeById method for QRCode of receipt (png image)
[+] added getters with defaults settings

**Comment by deniskristov** [comment]
Thank you for the new features!!!
There is the only recommendation, as mentioned in the [Abstract principle](https://en.wikipedia.org/wiki/Abstraction_principle_(computer_programming)):

`
Each significant piece of functionality in a program should be implemented in just one place in the source code. Where similar functions are carried out by distinct pieces of code, it is generally beneficial to combine them into one by abstracting out the varying parts.
`

so I'd prefer to have the only one `getForObjectImpl()` with

```
HttpResponse<byte[]> response = httpClient.send(request.build(), HttpResponse.BodyHandlers.ofByteArray());
```

instead of both `getForObjectImpl()` and `getForBytesImpl()` as they are pretty the same. To use this `HttpResponse<byte[]>` instead of `HttpResponse<String>` you have to change several parent methods, but this changes are simple.

**Comment by deniskristov** [comment]
And, please, use code formatting. For example it's better to have spaces in such peaces of code for better reading:

`id+"/text"+(width>=10 && width<=250?"?width="+width:""`

and also I'd prefer  to assign optional param to a variable instead of a long string:

```
public String getReportTextById(String id,int width)
{
    return getForString(URI.create(apiPrefix + REPORTS_PATH + "/" + id+"/text"+(width>=10 && width<=250?"?width="+width:"")));
}
```
use something like this:

```
    public String getReportTextById(String id,int width)
    {
        String widthParam = 
            width >= MIN_WIDTH && width <= MAX_WIDTH 
                ? "?width=" + width 
                : "";
        return getForString(URI.create(apiPrefix + REPORTS_PATH + "/" + id + "/text" + widthParam));
    }
```

and of cause no [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming))
use constants please

**Comment by deniskristov** [comment]
And one more thing )
Please, pay attention to ```getReceiptTextById(String id)``` as it recursively calls itself (looks like it shouldn't).

**Comment by dimaloop** [comment]
> And one more thing ) Please, pay attention to `getReceiptTextById(String id)` as it recursively calls itself (looks like it shouldn't).

Fixed, thank you


> And, please, use code formatting. 

changed

> instead of both `getForObjectImpl()` and `getForBytesImpl()` as they are pretty the same. To use this `HttpResponse<byte[]>` instead of `HttpResponse<String>` you have to change several parent methods, but this changes are simple.

Can you provide code example? have no glue how to get responseFunction's type and implement instanceOf generic type

**Comment by deniskristov** [comment]
[CheckboxApiClient.java.zip](https://github.com/deniskristov/checkbox-api-client/files/7943578/CheckboxApiClient.java.zip)

Sure, I'm sharing my implementations

**Comment by dimaloop** [comment]
Tested, works as expected! Thank you!

**Review by deniskristov — COMMENTED** [review]
I guess it's just a typo, but should be fixed:

```
 MAX_CHARS_PNG_RECEIPT <= 100
 ```

**Comment by dimaloop** [comment]
> I guess it's just a typo, but should be fixed:
> 
> ```
>  MAX_CHARS_PNG_RECEIPT <= 100
> ```

hard day, sorry.
Thank you for your attention

**Review by deniskristov — APPROVED** [review]
Looks good, merging

**Pull request merged**
