### PR TITLE
Added ReceiptFilter

### PR DESCRIPTION
**Pull request by dimaloop**
Hello, please review this PR

- added **ReceiptFilter** for new Receipt Search endpoint according to [api docs](https://dev-api.checkbox.in.ua/api/redoc#operation/get_receipts_search_api_v1_receipts_search_get)
- added new method **findReceipts** to wrapper
- removed unnecessary UnsupportedEncodingException
- update version at .pom

this is my first PR, I will be grateful for the comments, if something is not correct

### CODE REVIEW

**Comment by dimaloop** [comment]
Also:
- I've change package name (add suffix "checkbox") for better naming
- update lombok to version 1.18.22 because old version has known exception on java17
- i suggest to use StringJoiner to uri builder

**Comment by deniskristov** [comment]
Thank you for your new features and updates!
I have just a few recommendations:
- That's a good idea to use StringJoiner! And I'd like to ask you to set "?" as a prefix (and set "" as an empty value to StringJoiner) instead of concatenating it in the return statement.
- Please, use existing root RECEIPTS_PATH const instead of creating new (just imagine a situation if this path is changed - there should be only one place to change)

**Comment by deniskristov** [comment]
And I noticed one more thing - please, put @Singular annotation to the collections in ReceiptFilter
https://www.baeldung.com/lombok-builder-singular

**Review by deniskristov — COMMENTED** [review]
1. That's a good idea to use StringJoiner! And I'd like to ask you to set "?" as a prefix (and set "" as an empty value to StringJoiner) instead of concatenating it in the return statement.
2. Please, use existing root RECEIPTS_PATH const instead of creating new (just imagine a situation if this path is changed - there should be only one place to change)
3. And I noticed one more thing - please, put @Singular annotation to the collections in ReceiptFilter

**Comment by dimaloop** [comment]
Thank you for an answer!
1. prefix did not work as expected with an "empty" StringJoiner - its always join prefix, even in a case of "empty" - so maybe you can point me with a small example?
2. Ok, done. I think endpoints are not always exists in "tree" structure, but ok, fixed
3. Sorry, my fault. I had no experience with lombok. Fixed

Feel free to edit my code, if it is possible

**Comment by deniskristov** [comment]
1. sure:
 ```
StringJoiner query = new StringJoiner("&","?", "");
query.setEmptyValue("");
Assert.assertEquals("", query.toString());
query.add("test1");
query.add("test2");
Assert.assertEquals("?test1&test2", query.toString());
```

**Comment by dimaloop** [comment]
Ohh, you right. With emptyValue it works as expected

**Comment by dimaloop** [comment]
I cannot split the following changes in another PR while current is open (don't know how, sorry), so there are new changes:

[+] added CARD type to Payment 
[+] extended TYPEs and fields of ReceiptModel according to api specs
[+] added value/extraValue fields to ReportTaxesModel

**Comment by deniskristov** [comment]
Great!
One more thing: I cannot find ```serial``` in the documentation and my test shows that it doesn't work.

By the way, as I remember ```CARD``` is deprecated, and ```CASHLESS``` should be used instead. But anyway, if it exists in docs it's a good idea to have it in enums.

**Comment by dimaloop** [comment]
1. You right, "serial" field field is not included in the search. Fixed
2. Cannot find any info about CARD is deprecated
[https://dev-api.checkbox.in.ua/api/redoc#operation/get_receipt_api_v1_receipts_new__receipt_id__get](https://dev-api.checkbox.in.ua/api/redoc#operation/get_receipt_api_v1_receipts_new__receipt_id__get)


type | string (Готівкова форма оплати (CASH))Enum: "CASH" "CARD" "CASHLESS"An enumeration.
-- | --

**Comment by deniskristov** [comment]
2. Here:
https://dev-api.checkbox.in.ua/api/redoc#operation/create_receipt_api_v1_receipts_sell_post

image

**Comment by dimaloop** [comment]
Ok, confirmed. API documentation is a bit unclear

I will remove this type

BTW, "label" - required field, without them, I've got error

**Pull request merged**
